### ISSUE TITLE
Got Error when start backend, is it related to db setup?

### ISSUE THREAD

**Issue by NickLee380** [zhennann/cabloy#1]
2018-08-17 14:58:02,540 WARN 10636 [-/127.0.0.1/-/5ms POST /api/a/base/auth/echo] nodejs.Error: 已锁定
    at ErrorClass.throw (D:\Study\WP\cabloy-demo\node_modules\egg-born-backend\lib\base\error.js:28:19)
    at Object.context.(anonymous function) [as throw] (D:\Study\WP\cabloy-demo\node_modules\egg-born-backend\lib\module\errors.js:31:39)
    at instance (D:\Study\WP\cabloy-demo\node_modules\egg-born-module-a-instance\dist\backend.js:305:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
code: 423
message: "已锁定"
status: 423
pid: 10636
hostname: Nick-PC

**Comment by zhennann** [comment]
1. 
If perform `npm run dev:backend`, do not change the db's name. Cabloy will use the default db which is created by `npm run test:backend`.
2.
If perform `npm run start:backend`, should create an instance by `npm run init:backend --subdomain='instance1' --password='123456'`.
